# Generated by Django 4.1.3 on 2022-11-07 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('justificativa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('subarea_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifsolve.area')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('nota', models.IntegerField()),
                ('visibilidade', models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OB', 'Objetiva'), ('DI', 'Discursiva')], max_length=2)),
                ('visibilidade', models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado'), ('IN', 'Inativo')], max_length=2)),
                ('assunto', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de publicação')),
                ('texto_base', models.TextField(blank=True, null=True)),
                ('enunciado', models.TextField()),
                ('expectativa_resposta', models.TextField(blank=True, null=True, verbose_name='Expectativa de resposta')),
                ('alternativa_correta', models.CharField(blank=True, max_length=1, null=True)),
                ('alternativa_a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_a', to='ifsolve.alternativa')),
                ('alternativa_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_b', to='ifsolve.alternativa')),
                ('alternativa_c', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_c', to='ifsolve.alternativa')),
                ('alternativa_d', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_d', to='ifsolve.alternativa')),
                ('alternativa_e', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_e', to='ifsolve.alternativa')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='ifsolve.area')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('nota_item', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifsolve.avaliacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifsolve.item')),
            ],
            options={
                'verbose_name_plural': 'Itens Avaliação',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ifsolve.usuario')),
            ],
            bases=('ifsolve.usuario',),
        ),
        migrations.CreateModel(
            name='Elaborador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ifsolve.usuario')),
                ('verificado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Elaboradores',
            },
            bases=('ifsolve.usuario',),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ifsolve.tag'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('nota_obtida', models.IntegerField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifsolve.item')),
                ('item_avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifsolve.itemavaliacao')),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifsolve.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='elaborador',
            field=models.ManyToManyField(to='ifsolve.elaborador'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='ifsolve.aluno'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='elaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifsolve.elaborador'),
        ),
    ]
