# Generated by Django 4.1.3 on 2022-11-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifsolve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='co_elaboradores',
            field=models.ManyToManyField(related_name='co_elaboradores', to='ifsolve.elaborador'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='elaborador',
        ),
        migrations.AddField(
            model_name='item',
            name='elaborador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifsolve.elaborador'),
        ),
    ]
