# Generated by Django 4.1.3 on 2022-11-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifsolve', '0003_alter_item_co_elaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='elaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifsolve.elaborador'),
        ),
    ]
