# Generated by Django 4.1.3 on 2022-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifsolve', '0004_alter_item_elaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('ME', 'MultiplaEscolha'), ('DI', 'Discursiva')], max_length=2),
        ),
    ]
