# Generated by Django 4.1.3 on 2023-01-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifsolve', '0007_avaliacao_co_elaboradores_alter_avaliacao_elaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemavaliacao',
            name='avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ifsolve.avaliacao'),
        ),
    ]
