# Generated by Django 4.1.3 on 2023-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifsolve', '0008_alter_itemavaliacao_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='justificativa',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(null=True),
        ),
    ]
