version: "3"

services:
  web:
    image: diogoodiego/ifsolve-backend-django
    networks:
      - default
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
